/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Creates a user (Argon2id password hash) and sends a verification email. Returns 202 (no token). Requires email verification before login.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                        display_name?: string;
                    };
                };
            };
            responses: {
                /** @description Account created; verification email sent. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["StandardError"];
                409: components["responses"]["StandardError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email + password
         * @description Requires `email_verified=true`. Returns PASETO + refresh token pair with `expires_at`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["StandardError"];
                /** @description Email not verified. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the PASETO token
         * @description Rotates refresh tokens within a family; reuse detection revokes the entire family. The fresh PASETO uses the user's CURRENT `email_verified` status.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Refresh successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["StandardError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify email address
         * @description Accepts the token as a URL path segment OR query param. Returns a token pair on success.
         */
        get: {
            parameters: {
                query: {
                    /** @description Hex verification token from the email link. */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Email verified. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                404: components["responses"]["StandardError"];
                /** @description Token expired. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the verification email
         * @description Per-user 60s cooldown; returns `Retry-After` header on 429.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Verification email re-sent (or no such user — no enumeration). */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["StandardError"];
                404: components["responses"]["StandardError"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Always returns 202 (no user enumeration).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Reset email sent if the account exists. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["StandardError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a password reset
         * @description Writes a Valkey cutoff to invalidate all existing tokens (forces re-login).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        token: string;
                        /** Format: password */
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Password reset. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                400: components["responses"]["StandardError"];
                404: components["responses"]["StandardError"];
                /** @description Token expired. */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Sign-In (native / Android)
         * @description Validates the Google `id_token`. 409 on email conflict (link flow).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id_token: string;
                    };
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["StandardError"];
                409: components["responses"]["StandardError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/web": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Sign-In (web OAuth code flow)
         * @description Exchanges an authorization code for an id_token server-side. PKCE optional.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        auth_code: string;
                        /** Format: uri */
                        redirect_uri: string;
                        /** @description PKCE verifier (optional). */
                        code_verifier?: string;
                    };
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["StandardError"];
                409: components["responses"]["StandardError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple Sign-In (native / iOS)
         * @description Validates the Apple `identity_token` against Apple JWKS. 409 on email conflict (link flow).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        identity_token: string;
                    };
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["StandardError"];
                409: components["responses"]["StandardError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple/web": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple Sign-In (web OAuth code flow)
         * @description Exchanges an authorization `code` for an `id_token` at `https://appleid.apple.com/auth/token` using a per-request-minted `client_secret` JWT (ES256, signed with the Apple `.p8` key). 409 on email conflict (link flow).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Apple authorization code. */
                        code: string;
                        /** Format: uri */
                        redirect_uri: string;
                    };
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["StandardError"];
                409: components["responses"]["StandardError"];
                /** @description Apple token endpoint unreachable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out (revoke refresh tokens + PASETO cutoff)
         * @description Revokes all refresh tokens by default (or a specific one if `refresh_token` is provided). Writes a Valkey cutoff for instant PASETO invalidation.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Optional — revoke only this token instead of all. */
                        refresh_token?: string;
                    };
                };
            };
            responses: {
                /** @description Logged out. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user profile
         * @description Partial update — only `display_name` is mutable currently.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        display_name: string;
                    };
                };
            };
            responses: {
                /** @description Updated profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change password
         * @description Verifies the old password, sets the new one, and writes a Valkey cutoff (forces re-login everywhere).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: password */
                        old_password: string;
                        /** Format: password */
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Password changed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/link/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link a Google identity to the current account
         * @description 409 if already linked to a different user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id_token: string;
                    };
                };
            };
            responses: {
                /** @description Linked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["StandardError"];
            };
        };
        /**
         * Unlink the Google identity
         * @description Lockout guard — refuses if no password is set.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unlinked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/link/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link an Apple identity to the current account
         * @description Validates the `identity_token` against Apple JWKS. 409 if already linked to a different user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        identity_token: string;
                    };
                };
            };
            responses: {
                /** @description Linked. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["StandardError"];
            };
        };
        /**
         * Unlink the Apple identity
         * @description Lockout guard — refuses if no password is set.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unlinked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Returns metadata only — the raw key value is NEVER returned (only the prefix for identification).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API keys for the current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIKeyListItem"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create an API key
         * @description Returns the full key ONCE. Max 5 active (non-revoked) keys per user.
         *     API keys CANNOT create/list/revoke other API keys.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Human-readable key label. */
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description API key created (full key shown only here). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIKeyCreated"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Maximum active keys reached. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Idempotent (already-revoked returns 204). Writes a negative Valkey cache entry so revocation is effective within milliseconds.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description API key identifier (UUID). */
                    id: components["parameters"]["ApiKeyId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked (or was already revoked). */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect a cloud session
         * @description Asynchronous session provisioning. Returns the current session state — `provisioning` (202) while the broker prepares the task, `ready` (200) with a proxy endpoint when the session is reachable, or `failed` (503) with a failure reason on terminal error. The client polls this same endpoint with backoff respecting `retry_after_ms`. Idempotent per user — concurrent calls return the same session. Routed by userID in Valkey.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Optional HL image version. */
                        version?: string;
                        /** @description Per-install device identity for the D-DEV-04 authorization gate. The broker refuses to provision for unauthorized devices (403 device_authorization_required). Absent on first connect triggers the email auth-code flow. */
                        device_id?: string;
                    };
                };
            };
            responses: {
                /** @description Session is ready — the client can open a WebSocket to the `proxy_endpoint`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionConnectResponse"];
                    };
                };
                /** @description Session is provisioning — retry after `retry_after_ms` milliseconds. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionConnectResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Device authorization required — the connecting device must complete the email auth-code flow before a session can be provisioned. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            error?: "device_authorization_required";
                        };
                    };
                };
                429: components["responses"]["RateLimited"];
                /** @description Session provisioning failed — see `failure_reason`. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionConnectResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect a cloud session (enter grace period)
         * @description Transitions the session to a 5-minute grace period, then schedules cleanup.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        session_id?: string;
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description Grace period entered. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionDisconnectResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session/connected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report session connected (proxy → broker)
         * @description Called by the conduct proxy when the WebSocket upgrade completes; cancels the connect timeout.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connected acknowledged. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionConnectedResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available HL image versions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available versions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionsResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscription tiers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All subscription tiers. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Tier"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subscription/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user's subscription
         * @description Resolves the tier from the auth context; defaults to `free` if no subscription exists.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current subscription. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionMe"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download this OpenAPI specification (YAML)
         * @description Serves the embedded OpenAPI 3.1 document in YAML. The `servers` array
         *     is rewritten to reflect the domain you accessed this endpoint from
         *     (`beta.*` preserved, `project-harmony.ai` legacy mapped to canonical
         *     `soulbits.app`, localhost passed through for dev). Public (no auth)
         *     to aid tooling (Postman, IDE import, code generation).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The OpenAPI document (YAML). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/yaml": components["schemas"]["OpenAPISpec"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download this OpenAPI specification (JSON)
         * @description Same as `/v1/openapi.yaml` but JSON-encoded.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The OpenAPI document (JSON). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpenAPISpec"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models
         * @description Public (no auth). Returns all active models with metadata. Supports OpenRouter-style superset modality filters.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Exact match on model type (`llm`, `tts`, `stt`, `vad`, `embeddings`, `rerank`, `voice_embed`, `audio_conversion`, `voice_conversion`). */
                    model_type?: components["parameters"]["ModelType"];
                    /** @description Superset match — model must accept ALL listed input modalities. Repeat the key for multiple values. */
                    input_modalities?: components["parameters"]["InputModalities"];
                    /** @description Superset match — model must emit ALL listed output modalities. Repeat the key for multiple values. */
                    output_modalities?: components["parameters"]["OutputModalities"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All active models (filtered). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ModelEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat completions (LLM)
         * @description OpenAI-compatible chat completions. The gateway forwards the body as
         *     opaque JSON to the LLM worker (Aphrodite/vLLM/sglang), rewriting only
         *     the `model` field. **Non-streaming** — `stream:true` is ignored (the
         *     gateway uses a queue-based RPC pattern; every request returns one
         *     complete response object). Max body 1 MB; timeout 120s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatCompletionRequest"];
                };
            };
            responses: {
                /** @description Chat completion. */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatCompletionResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                /** @description Gateway timeout — inference request timed out (includes `task_id`). */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text embeddings
         * @description OpenAI-compatible text embeddings (served by the Infinity engine). Supports Matryoshka `dimensions` and multimodal `modality`. Max body 1 MB; timeout 10s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmbeddingRequest"];
                };
            };
            responses: {
                /** @description Embeddings. */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmbeddingResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rerank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerank documents by relevance to a query
         * @description Cohere-compatible (served by the Infinity engine). Max body 1 MB; timeout 10s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RerankRequest"];
                };
            };
            responses: {
                /** @description Rerank results. */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RerankResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text-to-Speech (TTS)
         * @description Harmony Speech Engine TTS. NOT OpenAI-shaped — requires `mode`; audio
         *     format via `output_options.format` (not `response_format`); cloning via
         *     `input_audio`/`input_embedding`. Max body 10 MB; timeout 120s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TTSRequest"];
                };
            };
            responses: {
                /** @description Synthesized audio (base64). */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AudioDataResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                /** @description Gateway timeout. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speech-to-Text (STT)
         * @description JSON-only (NOT multipart). Audio is base64-encoded inside the JSON body. Max body 10 MB; timeout 300s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["STTRequest"];
                };
            };
            responses: {
                /** @description Transcription. */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["STTResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                /** @description Gateway timeout. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/vad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Activity Detection (VAD)
         * @description Detects speech segments in audio. Returns timestamps and speech-confidence metadata. Max body 10 MB; timeout 10s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VADRequest"];
                };
            };
            responses: {
                /** @description VAD result. */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VADResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embed/speaker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speaker embedding
         * @description Creates a voice embedding from an audio sample; can be passed as `input_embedding` (TTS) or `target_embedding` (voice conversion) to skip re-sending reference audio. Max body 10 MB; timeout 30s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpeakerEmbedRequest"];
                };
            };
            responses: {
                /** @description Speaker embedding (base64). */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AudioDataResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audio/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audio conversion / enhancement
         * @description Audio enhancement / format conversion (e.g. denoising, restoration via VoiceFixer). Max body 10 MB; timeout 120s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AudioConversionRequest"];
                };
            };
            responses: {
                /** @description Enhanced/converted audio (base64). */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AudioDataResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                /** @description Gateway timeout. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voice/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice conversion
         * @description Converts the voice in source audio to sound like a target speaker (reference audio or pre-computed embedding). At least one of `target_audio`/`target_embedding` is required. Max body 10 MB; timeout 120s.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VoiceConversionRequest"];
                };
            };
            responses: {
                /** @description Converted audio (base64). */
                200: {
                    headers: {
                        "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                        "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                        "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AudioDataResponse"];
                    };
                };
                400: components["responses"]["StandardError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                429: components["responses"]["RateLimited"];
                /** @description Gateway timeout. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate images (currently unavailable)
         * @deprecated
         * @description ⚠️ NOT CURRENTLY SERVED. The route, quota logic, and rate-limit wiring
         *     exist in the gateway, but **no image-generation worker is deployed**
         *     and **no image model is present in the catalog**. Requests will fail
         *     (gateway timeout or 5xx). This endpoint will be re-enabled once an
         *     image backend (ComfyUI on Salad) is deployed. Quota enforcement order
         *     (when re-enabled): auth+tier → rate limit → tier daily cap → Soul
         *     Credits → 402.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImageGenerationRequest"];
                };
            };
            responses: {
                /** @description Quota exceeded (when re-enabled — upgrade or buy Soul Credits). */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Service Unavailable — no image backend deployed. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date-time
         * @description RFC 3339 timestamp (e.g. `2026-06-28T19:00:00Z`).
         */
        RFC3339Timestamp: string;
        /**
         * Format: byte
         * @description Base64-encoded audio bytes (sent inside JSON; NOT multipart).
         */
        Base64Audio: string;
        /**
         * Format: byte
         * @description Base64-encoded binary payload (embedding, image, etc.).
         */
        Base64Blob: string;
        Message: {
            message: string;
        };
        /**
         * @description Error envelope. The exact field set varies slightly by service:
         *       * Inference gateway: `{ "error": "<code>", "message": "<text>" }`
         *       * Auth-service:      `{ "error": "<message>" }`
         *       * Session-broker:    `{ "error_code": "<code>", "message": "<text>" }`
         *     All variants validate against this schema (extra fields allowed).
         */
        Error: {
            /** @description Error code (inference/session) OR message (auth-service). */
            error?: string;
            /** @description Error code (session-broker variant). */
            error_code?: string;
            /** @description Human-readable message. */
            message?: string;
            /**
             * Format: uri
             * @description Present on 402 quota_exceeded for image generation.
             */
            upgrade_url?: string;
            /** @description Present on 402 — the user's current tier id. */
            current_tier?: string;
            /** @description Present on 402 — the minimum tier required. */
            required_tier?: string;
            /** @description Present on 402 — remaining Soul Credits. */
            soul_credits_available?: number;
            /** @description Present on 504 gateway_timeout — for debugging. */
            task_id?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Issued on successful login/register-verify/refresh/OAuth. The `expires_at` field lets clients schedule proactive PASETO refresh without decoding the encrypted v4.local payload. */
        TokenResponse: {
            /** @description PASETO v4.local Bearer token (`v4.local.*`). */
            token: string;
            /** @description Opaque refresh token. Rotated on each refresh; reuse detection revokes the whole family. */
            refresh_token: string;
            expires_at: components["schemas"]["RFC3339Timestamp"];
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            email_verified: boolean;
            created_at: components["schemas"]["RFC3339Timestamp"];
        };
        /** @description Returned ONLY at creation time. The `key` field is shown once — store it securely. */
        APIKeyCreated: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Full API key (`sb_cloud_` + base64url). Returned ONLY here; never retrievable later. */
            key: string;
            /** @description First 12 characters of the key, for identification. */
            prefix: string;
            created_at: components["schemas"]["RFC3339Timestamp"];
        };
        APIKeyListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description First 12 chars (raw key never returned). */
            prefix: string;
            created_at: components["schemas"]["RFC3339Timestamp"];
            last_used_at: components["schemas"]["RFC3339Timestamp"] | null;
            revoked_at: components["schemas"]["RFC3339Timestamp"] | null;
        };
        SessionConnectResponse: {
            /** Format: uuid */
            session_id: string;
            /** @description Conduct proxy WebSocket base URL for this session (e.g. `wss://connect.soulbits.app`). Present when status is `ready` or `active`. */
            proxy_endpoint?: string;
            /** @enum {string} */
            status: "provisioning" | "ready" | "active" | "failed";
            /** @description Milliseconds to wait before polling again. Present when status is `provisioning`. */
            retry_after_ms?: number;
            /** @description Human-readable failure reason. Present when status is `failed`. */
            failure_reason?: string;
            /** @description HL image version assigned from the warm pool. */
            image_version?: string | null;
        };
        SessionDisconnectResponse: {
            /** @enum {string} */
            status: "grace_period";
            grace_period_until: components["schemas"]["RFC3339Timestamp"];
        };
        SessionConnectedResponse: {
            /** @enum {string} */
            status: "connected";
        };
        VersionsResponse: {
            versions: string[];
            default: string;
            default_image: string;
        };
        /** @description Per-tier rate/quota limits. `null` means unlimited/not applicable. */
        TierLimits: {
            chat_requests_per_min?: number | null;
            chat_requests_per_day?: number | null;
            voice_minutes_per_day?: number | null;
            video_gen_per_day?: number | null;
            video_10s_per_day?: number | null;
            video_60s_per_day?: number | null;
            image_gen_per_day?: number | null;
            message_length_tokens?: number | null;
            audio_requests_per_min?: number | null;
            vad_embed_per_min?: number | null;
        } & {
            [key: string]: unknown;
        };
        Tier: {
            /** @description Tier id (`free`, `core`, `infinite`). */
            id: string;
            display_name: string;
            sort_order: number;
            limits: components["schemas"]["TierLimits"];
            /** @description Arbitrary feature flags. */
            features: {
                [key: string]: unknown;
            };
        };
        SubscriptionMe: {
            tier_id: string;
            display_name: string;
            /** @enum {string} */
            status: "active" | "past_due" | "canceled" | "trialing";
            expires_at: components["schemas"]["RFC3339Timestamp"] | null;
            limits: components["schemas"]["TierLimits"];
            features: {
                [key: string]: unknown;
            };
        };
        SpeechLanguage: {
            /** @description ISO 639 code (e.g. `EN`, `ZH`, `ES`, `FR`, `JA`). */
            code: string;
            name: string;
            /** @description Valid `voice` values for this language. */
            voices?: string[];
        };
        /** @description Present only on speech models. Field presence maps to a real request parameter the model accepts. */
        SpeechOptions: {
            /** @description Present iff the model accepts the `language` request param. */
            languages?: components["schemas"]["SpeechLanguage"][];
            /** @description Present iff the model accepts `voice` WITHOUT a language scope (e.g. KittenTTS). */
            voices?: string[];
            supports_single_speaker?: boolean | null;
            supports_voice_cloning?: boolean | null;
            /** @description Effect/emotion tokens embedded directly in the TTS `input` text (e.g. `[whispering]`). No special request field needed. */
            paralinguistic_tags?: string[];
        };
        ModelEntry: {
            model_id: string;
            display_name: string;
            /** @enum {string} */
            model_type: "llm" | "tts" | "stt" | "vad" | "image" | "embeddings" | "rerank" | "voice_embed" | "audio_conversion" | "voice_conversion";
            /** @enum {string} */
            min_tier: "free" | "core" | "infinite";
            /** @description i18n key (e.g. `models.descriptions.qwen-35-9b`) resolved by the portal; not plaintext. */
            description: string;
            /** @description e.g. `["text","image","video"]`. Empty array if omitted. */
            input_modalities?: string[];
            output_modalities?: string[];
            /** @description Token context window (LLM/embeddings). */
            context_window?: number | null;
            /** @description Output vector dimensionality (embeddings). */
            embedding_dimensions?: number | null;
            speech_options?: components["schemas"]["SpeechOptions"];
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool";
            /** @description OpenAI-style content; string for text-only, array for multi-modal. */
            content: string | {
                type?: string;
                text?: string;
                image_url?: {
                    url?: string;
                };
            }[];
        };
        /**
         * @description OpenAI-compatible chat completions request body. The gateway forwards
         *     the body as opaque JSON to the LLM worker (Aphrodite/vLLM/sglang),
         *     rewriting only the `model` field. Standard OpenAI pass-through params
         *     (`stop`, `seed`, `response_format`, `logprobs`, `tools`,
         *     `tool_choice`) are supported by the backend engine. `stream` is not
         *     supported today.
         */
        ChatCompletionRequest: {
            /**
             * @description Model ID (e.g. `qwen-35-9b`).
             * @example qwen-35-9b
             */
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            temperature?: number;
            max_tokens?: number;
            top_p?: number;
            frequency_penalty?: number;
            presence_penalty?: number;
            /** @description Reproducible sampling seed. */
            seed?: number;
            /** @description Stop sequence(s). */
            stop?: string | string[];
            /** @description OpenAI response format (`{"type":"text"}` or `{"type":"json_object"}`). */
            response_format?: {
                /** @enum {string} */
                type?: "text" | "json_object";
            };
            /** @description Return log probabilities. */
            logprobs?: boolean;
            /** @description Number of top logprobs per token (requires `logprobs:true`). */
            top_logprobs?: number;
            /** @description OpenAI function-calling tool definitions. */
            tools?: Record<string, never>[];
            tool_choice?: ("none" | "auto" | "required") | Record<string, never>;
            /**
             * @description **NOT SUPPORTED** — the gateway uses a queue-based RPC pattern; every request returns one complete response object. A `true` value is ignored.
             * @default false
             */
            stream: boolean;
        } & {
            [key: string]: unknown;
        };
        ChatCompletionResponse: {
            id: string;
            /** @enum {string} */
            object: "chat.completion";
            /** Format: int64 */
            created: number;
            model: string;
            choices: {
                index?: number;
                message?: components["schemas"]["ChatMessage"];
                /** @enum {string} */
                finish_reason?: "stop" | "length" | "tool_calls" | "content_filter";
            }[];
            usage?: {
                prompt_tokens?: number;
                completion_tokens?: number;
                total_tokens?: number;
            };
        };
        EmbeddingRequest: {
            /** @example qwen3-embed-4b */
            model: string;
            /** @description Text (or array of texts) to embed. For multimodal models, `input` may be a base64 data URI or URL when `modality` is `image`/`audio`. */
            input: string | string[];
            /**
             * @default float
             * @enum {string}
             */
            encoding_format: "float" | "base64";
            /** @description Infinity-engine Matryoshka dimensionality reduction. Default `0` = model's native dims. Omit for native dimensions. */
            dimensions?: number;
            /**
             * @description Infinity-engine input discriminator. When `image`/`audio`, `input` accepts URLs/base64 data URIs.
             * @default text
             * @enum {string}
             */
            modality: "text" | "image" | "audio";
            /** @description OpenAI-compatible end-user identifier (optional). */
            user?: string;
        } & {
            [key: string]: unknown;
        };
        EmbeddingResponse: {
            /** @description Infinity includes an `id`; OpenAI omits it. */
            id?: string;
            /** @enum {string} */
            object: "list";
            /**
             * Format: int64
             * @description Infinity includes `created`; OpenAI omits it.
             */
            created?: number;
            data: {
                /** @enum {string} */
                object?: "embedding";
                index?: number;
                embedding?: number[] | string;
            }[];
            model: string;
            usage: {
                prompt_tokens?: number;
                total_tokens?: number;
            };
        };
        RerankRequest: {
            /** @example qwen3-rerank-0-6b */
            model: string;
            query: string;
            /** @description Document strings to rank against the query. */
            documents: string[];
            /** @description Return only the top N results. Default = all. */
            top_n?: number;
            /**
             * @description Infinity — include the document text in each result.
             * @default false
             */
            return_documents: boolean;
            /**
             * @description Infinity — return raw logits instead of normalized scores.
             * @default false
             */
            raw_scores: boolean;
        } & {
            [key: string]: unknown;
        };
        RerankResponse: {
            /** @description Infinity response id. */
            id?: string;
            /** @enum {string} */
            object?: "rerank";
            /** Format: int64 */
            created?: number;
            model?: string;
            results: {
                index: number;
                relevance_score: number;
                /** @description Present when `return_documents=true`. */
                document?: string;
            }[];
            usage?: {
                prompt_tokens?: number;
                total_tokens?: number;
            };
        };
        /** @description Generation parameters for TTS / voice conversion. Most fields are model-specific; unsupported fields are silently ignored. */
        GenerationOptions: {
            seed?: number | null;
            /** @description Style index (model-dependent). */
            style?: number | null;
            speed?: number | null;
            pitch?: number | null;
            energy?: number | null;
            /** @description (Chatterbox) Emotion exaggeration factor (default 0.5). */
            exaggeration?: number | null;
            /** @description (Chatterbox) Classifier-free guidance weight (default 0.5). */
            cfg_weight?: number | null;
            /** @description (Chatterbox) Sampling temperature (default 0.8). */
            temperature?: number | null;
            /** @description (Chatterbox) Repetition penalty >1.0 reduces repetition (default 1.2). */
            repetition_penalty?: number | null;
            /** @description (Chatterbox) Top-p nucleus sampling probability. */
            top_p?: number | null;
            /** @description (Chatterbox TTS/Multilingual) Minimum probability threshold (default 0.05). */
            min_p?: number | null;
            /** @description (Chatterbox Turbo) Top-k sampling candidates (default 1000). */
            top_k?: number | null;
            /** @description (Chatterbox Turbo) Apply pyloudnorm loudness normalization (default true). */
            norm_loudness?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Output audio format. */
        OutputOptions: {
            /**
             * @default wav
             * @enum {string}
             */
            format: "wav" | "mp3" | "flac";
            /** @description Resample output to this rate (Hz); null = model's native rate. */
            sample_rate?: number | null;
            /**
             * @description Reserved for future use.
             * @default false
             */
            stream: boolean;
        };
        /** @description Filters applied before synthesis/conversion. Each filter is itself an AudioConversionRequest-shaped opaque object (recursive filter chain). */
        PreProcessingFilters: {
            [key: string]: unknown;
        }[];
        /**
         * @description Harmony Speech Engine TTS request. NOT OpenAI-shaped — requires `mode`,
         *     audio format via `output_options.format` (not `response_format`), and
         *     cloning via `input_audio`/`input_embedding`.
         */
        TTSRequest: {
            /** @description TTS model or toolchain group (e.g. `kitten-tts-mini`, `chatterbox`, `openvoice_v2`). */
            model: string;
            /** @description Text to synthesize. `chatterbox_turbo` accepts paralinguistic tags inline. */
            input: string;
            /**
             * @description `single_speaker_tts` skips VAD/embedding/tone-conversion; `voice_cloning` runs the full pipeline.
             * @enum {string}
             */
            mode: "single_speaker_tts" | "voice_cloning";
            /** @description Language code — required only by multilingual models (`openvoice_v1/v2`, `chatterbox_multilingual`). See the catalog `speech_options.languages`. */
            language?: string;
            /** @description Preset voice ID — required when the model/language has preset voices. */
            voice?: string;
            input_audio?: components["schemas"]["Base64Audio"];
            /** @description Pre-computed speaker embedding (faster than `input_audio`; skips VAD/embedding). */
            input_embedding?: components["schemas"]["Base64Blob"];
            /** @description VAD result JSON from `/v1/audio/vad`; skips the internal VAD step. */
            input_vad_data?: string;
            /** @description VAD engine hint (informational). */
            input_vad_mode?: string;
            generation_options?: components["schemas"]["GenerationOptions"];
            output_options?: components["schemas"]["OutputOptions"];
            pre_processing_filters?: components["schemas"]["PreProcessingFilters"];
            /** @description Filters applied after synthesis (recursive filter chain). */
            post_generation_filters?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        AudioDataResponse: {
            id: string;
            model: string;
            /** Format: int64 */
            created: number;
            data: components["schemas"]["Base64Blob"];
        };
        /** @description JSON-only (NOT multipart). Audio is base64-encoded inside the JSON body. */
        STTRequest: {
            /** @example faster-whisper-large-v3-turbo */
            model: string;
            input_audio: components["schemas"]["Base64Audio"];
            /**
             * @description Return the detected source language tag.
             * @default false
             */
            get_language: boolean;
            /**
             * @description Return word-level timestamps.
             * @default false
             */
            get_timestamps: boolean;
        } & {
            [key: string]: unknown;
        };
        STTResponse: {
            id: string;
            model: string;
            /** Format: int64 */
            created: number;
            text: string;
            /** @description Present when `get_language=true`. */
            language?: string;
            /** @description Present when `get_timestamps=true`. */
            timestamps?: {
                word?: string;
                start?: number;
                end?: number;
            }[];
        };
        VADRequest: {
            /** @description VAD model (`silero-vad`; `faster-whisper-*` also accepted but less precise). */
            model: string;
            input_audio: components["schemas"]["Base64Audio"];
            /** @default false */
            get_timestamps: boolean;
            /** @description Detection sensitivity — Silero only (default 0.5). */
            threshold?: number | null;
            /** @description Silero only (default 250). */
            min_speech_duration_ms?: number | null;
            /** @description Silero only (default 100). */
            min_silence_duration_ms?: number | null;
            /** @description Silero only (default 30). */
            speech_pad_ms?: number | null;
            /** @description Silero only — return timestamps in seconds instead of ms. */
            return_seconds?: boolean;
        } & {
            [key: string]: unknown;
        };
        VADResponse: {
            id: string;
            model: string;
            /** Format: int64 */
            created: number;
            speech_activity: boolean;
            /** @description Present when `get_timestamps=true`. */
            timestamps?: {
                /** @description ms (or seconds if `return_seconds=true`). */
                start?: number;
                end?: number;
            }[];
        };
        SpeakerEmbedRequest: {
            /** @description Embedding-capable model (e.g. `harmonyspeech`, `chatterbox`, `openvoice_v1`, `openvoice_v2`). */
            model: string;
            input_audio: components["schemas"]["Base64Audio"];
        } & {
            [key: string]: unknown;
        };
        AudioConversionRequest: {
            /** @example voicefixer */
            model: string;
            source_audio: components["schemas"]["Base64Audio"];
            output_options?: components["schemas"]["OutputOptions"];
            pre_processing_filters?: components["schemas"]["PreProcessingFilters"];
        } & {
            [key: string]: unknown;
        };
        /** @description At least one of `target_audio` or `target_embedding` is required. */
        VoiceConversionRequest: {
            /** @example chatterbox_vc */
            model: string;
            source_audio: components["schemas"]["Base64Audio"];
            target_audio?: components["schemas"]["Base64Audio"];
            /** @description Pre-computed speaker embedding (faster than `target_audio`). */
            target_embedding?: components["schemas"]["Base64Blob"];
            generation_options?: components["schemas"]["GenerationOptions"];
            output_options?: components["schemas"]["OutputOptions"];
            pre_processing_filters?: components["schemas"]["PreProcessingFilters"];
        } & {
            [key: string]: unknown;
        };
        /**
         * @deprecated
         * @description OpenAI-compatible image generation. Currently NOT served — no worker is deployed.
         */
        ImageGenerationRequest: {
            model: string;
            prompt: string;
            /** @default 1 */
            n: number;
            /**
             * @default 1024x1024
             * @enum {string}
             */
            size: "256x256" | "512x512" | "1024x1024";
        } & {
            [key: string]: unknown;
        };
        /** @description The full OpenAPI document (JSON or YAML). Served with `servers` rewritten to the caller's access domain. */
        OpenAPISpec: {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Error response. Inference gateway shape: `{"error":"<code>","message":"<text>"}`. Auth-service shape: `{"error":"<message>"}`. Session-broker shape: `{"error_code":"<code>","message":"<text>"}`. */
        StandardError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 429 Too Many Requests — rate limit exceeded. Includes `Retry-After` header. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 401 Unauthorized — missing, expired, revoked, or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 403 Forbidden — model requires a higher subscription tier. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 404 Not Found — model not found or resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 500 Internal Server Error — retry with backoff. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description API key identifier (UUID). */
        ApiKeyId: string;
        /** @description Exact match on model type (`llm`, `tts`, `stt`, `vad`, `embeddings`, `rerank`, `voice_embed`, `audio_conversion`, `voice_conversion`). */
        ModelType: string;
        /** @description Superset match — model must accept ALL listed input modalities. Repeat the key for multiple values. */
        InputModalities: string[];
        /** @description Superset match — model must emit ALL listed output modalities. Repeat the key for multiple values. */
        OutputModalities: string[];
    };
    requestBodies: never;
    headers: {
        /** @description Maximum requests allowed in the current window. */
        RateLimitLimit: number;
        /** @description Remaining requests in the current window (computed after incrementing the counter). */
        RateLimitRemaining: number;
        /** @description Unix timestamp (seconds) when the window resets. */
        RateLimitReset: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
